### ISSUE TITLE
puppet node purge Api call failing with multi certnames

### ISSUE THREAD

**Issue by singhravinderlko** [natemccurdy/puppet-purge_node#12]
data='{"environment": "test", "scope" : { "nodes" : ["pe master node name"] }, "params" : { "agent_certnames" : ["abc","def"] }, "task": "support_tasks::st0317b_purge_node"}'

curl --insecure --header "$type_header" --header "$auth_header" --request POST "$uri" --data "$data"                                            {
  "kind" : "puppetlabs.validators/validation-error",
  "msg" : "The agent_certnames parameter expected a value of type Pattern[/^([A-Za-z0-9._-]+,?)+$/] but got \"[\"abc\" \"def\"]\"",
  "details" : {
    "parameter" : "agent_certnames",
    "type" : "Pattern[/^([A-Za-z0-9._-]+,?)+$/]",
    "value" : [ "abc", "def" ]
  }

getting above pattern validation error while pattern is correct.

**Comment by natemccurdy** [comment]
@singhravinderlko  Looks like you're using the Puppet Enterprise support tasks module (https://github.com/puppetlabs/support-tasks) which contains a fork of my module's task.

I recommend you bring this up via a Puppet Enterprise support ticket: https://support.puppet.com/hc/en-us

Not sure if they've modified my code at all, but either way I can't provide support for their module.
