### ISSUE TITLE
Find a better way to detect a Puppet master

### ISSUE THREAD

**Issue by natemccurdy** [natemccurdy/puppet-purge_node#2]
The current logic to detect if the task is being run on a the primary master doesn't account for some edge cases. For example, when using SRV records and the value for `server` **does not** equal `certname`.

https://github.com/natemccurdy/puppet-purge_node/blob/1.2.0/tasks/init.rb#L14

Find a better way to figure this out.

**Comment by natemccurdy** [comment]
One possible way is to search `/etc/puppetlabs/puppetserver/bootstrap.cfg` for the `certificate-authority-service` line as that *should* only exist on the CA.

**Comment by jacobmw** [comment]
We also have this issue as we have HA enabled.

**Comment by natemccurdy** [comment]
@jacobmw If you have a moment, can you check if the solution from the [detect_master](https://github.com/natemccurdy/puppet-purge_node/commit/49860852af525dbfbd280e1febe1b7bc557b3fcb) branch works for you?

**Comment by natemccurdy** [comment]
Fixed in https://github.com/natemccurdy/puppet-purge_node/releases/tag/1.2.1
